apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authcheck.fullname" . }}-config
  labels:
    {{- include "authcheck.labels" . | nindent 4 }}
data:
  appsettings.Production.json: |
    {
      "AuthCheck": {
        "OAuth": {{ .Values.authCheck.oAuth | default true }},
        "DelayInMinutes": {{ .Values.authCheck.delayInMinutes }},
        "OAuthChecks": [
          {{- range $index, $check := .Values.authCheck.oAuthChecks }}
          {{- if $index }},{{ end }}
          {
            "Name": {{ $check.name | quote }},
            "Server": {{ $check.server | quote }},
            "ClientId": {{ $check.clientId | quote }},
            "ClientSecret": {{ $check.clientSecret | quote }},
            "Scope": {{ $check.scope | quote }}
          }
          {{- end }}
        ]
      }
    }